#!/bin/sh
IP=$1
echo "COMPILING..."
rm -rf ./Divisé.app
rm -rf ./Build/Release-iphoneos/Divisé.app
rm -rf ./com.moski.Divise
xcodebuild -target Divisé -xcconfig compile64.xcconfig -configuration Release >> /dev/null
mv ./Build/Release-iphoneos/Divisé.app ./Divisé.app
echo "COMPILING SUCCDATROOT..."
cd ./succdatroot/ && make
cd ..
cp ./succdatroot/.theos/obj/debug/succdatroot ./Divisé.app/succdatroot
mv ./Divisé.app/succdatroot ./Divisé.app/succdatroot2
mv ./Divisé.app/succdatroot2/succdatroot ./Divisé.app/succdatroot
rm -rf ./Divisé.app/succdatroot2 ## This is annoying and badly done but it works
ldid -SSuccessionEntitlements.plist ./Divisé.app/Divisé
rm -rf ./Divisé.app/attach
ldid -SSuccessionEntitlements.plist ./Divisé.app/succdatroot
rm -rf ./Divisé.app/hdik-armv7
ldid -SSuccessionEntitlements.plist ./Divisé.app/hdik-arm64
rm -rf ./Divisé.app/hdik-arm64e
ldid -SSuccessionEntitlements.plist ./Divisé.app/apfs_deletefs
rm -f ./Divisé.app/embedded.mobileprovision
mkdir ./com.moski.Divise
cp -r ./Template/* ./com.moski.Divise/
mkdir com.moski.Divise/Applications/
mv Divisé.app com.moski.Divise/Applications/
sudo fakeroot chmod 6755 com.moski.Divise/Applications/Divisé.app/Divisé
sudo fakeroot chmod 0755 com.moski.Divise/Applications/Divisé.app/succdatroot
sudo fakeroot chmod 0755 com.moski.Divise/Applications/Divisé.app/hdik-arm64
sudo fakeroot chmod 0755 com.moski.Divise/Applications/Divisé.app/apfs_deletefs

rm -rf ./Index
find . -type f -name .DS_Store -delete && xattr -cr *
sudo fakeroot dpkg-deb -Zgzip -b com.moski.Divise com.moski.Divise.1.0.1.deb

if [ -z "$IP" ]
then
    echo "Getting ready for release!"
    echo "Size:"
    ls -la com.moski.Divise.1.0.1.deb
    echo "md5:"
    md5 com.moski.Divise.1.0.1.deb
    echo "sha1:"
    shasum -a 1 com.moski.Divise.1.0.1.deb
    echo "sha256:"
    shasum -a 256 com.moski.Divise.1.0.1.deb
    echo "Done!"
    exit
fi
echo "INSTALLING TO DEVICE"

echo "Trying to move deb to device"
scp com.moski.Divise.1.0.1.deb root@$IP:/tmp
echo "Trying to install deb"
ssh root@$IP "dpkg -i /tmp/com.moski.Divise.1.0.1.deb && uicache --path /Applications/Divisé.app/"
echo "Success!"

## Changes made by nobbele/4ppleCracker/moski
