ARCHS = arm64
TARGET = iphone::10.3:8.0
include ~/.theos/makefiles/common.mk

TOOL_NAME = succdatroot
succdatroot_FILES = main.c
succdatroot_CODESIGN_FLAGS = -Sent.plist

include ~/.theos/makefiles/tool.mk
